batch_size: 16
epoch: 200
learning_rate: 0.01
gpu: 0
num_point: 3000
optimizer: Adam
weight_decay: 1e-6
normal: True
lr_decay: 0.5
step_size: 50

defaults:
   #- model: Zhao
   - model: Hengshuang

hydra:
  run:
    dir: log/partseg/${model.name}

  sweep:
    dir: log/partseg
    subdir: ${model.name}

    
