batch_size: 16
epoch: 1000
learning_rate: 0.001
gpu: 0
num_point: 2048
optimizer: Adam
weight_decay: 1e-6
normal: True
lr_decay: 0.5
step_size: 400

defaults:
   #- model: Zhao
   - model: Hengshuang

hydra:
  run:
    dir: log/partseg/${model.name}

  sweep:
    dir: log/partseg
    subdir: ${model.name}

    
