batch_size: 8
epoch: 100
learning_rate: 0.01
gpu: 0
num_point: 512
optimizer: SGD
weight_decay: 0.0001
normal: True
lr_decay: 0.5
step_size: 20

defaults:
  - model: Hengshuang

hydra:
  run:
    dir: log/partseg/${model.name}

  sweep:
    dir: log/partseg
    subdir: ${model.name}

    
